In [ ]:
import tensorflow as tf

# Vecotors and Metrice

In [ ]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([2,0,-3.])
print(tensor_one_d)

tf.Tensor([ 2.  0. -3.], shape=(3,), dtype=float32)


In [ ]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,9]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  9]], shape=(4, 3), dtype=int32)


In [ ]:
tensor_three_d = tf.constant(
[
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]]
])
print(tensor_three_d)

tf.Tensor(
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]], shape=(4, 2, 3), dtype=int32)


## Shape of tensor

In [ ]:
print(tensor_three_d.shape)

(4, 2, 3)


## Dimensions of Matrix

In [ ]:
print(tensor_three_d.ndim)

3


In [ ]:
tensor_four_d = tf.constant(
[
  [
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]]
  ],
  [
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]]
  ]
]
)
print(tensor_four_d)

tf.Tensor(
[[[[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]]


 [[[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]]], shape=(2, 4, 2, 3), dtype=int32)


## Tensor Casting

In [ ]:
tensor_one_d = tf.constant([1,2,3,4,5], dtype=tf.float32)
print(tensor_one_d)
casted_tensor = tf.cast(tensor_one_d,dtype=tf.int16)
print(casted_tensor)

tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int16)


In [ ]:
casted_tensor_bool = tf.cast(tensor_one_d,dtype=tf.bool)
print(casted_tensor_bool)

tf.Tensor([ True  True  True  True  True], shape=(5,), dtype=bool)


In [ ]:
tensor_string = tf.constant("Hello World")
print(tensor_string)

tf.Tensor(b'Hello World', shape=(), dtype=string)


## Convert Numpy Array to Tensor

In [ ]:
import numpy as np

In [ ]:
np_array = np.array([1,2,4,5])
print(np_array)

[1 2 4 5]


In [ ]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4 5], shape=(4,), dtype=int64)


## Identity Matrix

In [ ]:
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=[2],
    dtype=tf.dtypes.float32,
    name=None
)

print(eye_tensor)

tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]], shape=(2, 3, 3), dtype=float32)


## Tenserflow Method

In [ ]:
fill_tensor = tf.fill(
    [3,4], value=5, name=None, layout=None
)
print(fill_tensor)

tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)


In [ ]:
ones_tensor = tf.ones([2,3])
print(ones_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [ ]:
ones_like_tensor = tf.ones_like(fill_tensor)
print(ones_like_tensor)

tf.Tensor(
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]], shape=(3, 4), dtype=int32)


In [ ]:
zeroes_tensor = tf.zeros([2,4])
print(zeroes_tensor)

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(2, 4), dtype=float32)


In [ ]:
zeroes_like_tensor = tf.zeros_like(fill_tensor)
print(zeroes_like_tensor)

tf.Tensor(
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)


In [ ]:
print(tf.shape(zeroes_like_tensor))

tf.Tensor([3 4], shape=(2,), dtype=int32)


In [ ]:
print(tf.rank(zeroes_like_tensor))

tf.Tensor(2, shape=(), dtype=int32)


In [ ]:
print(tf.size(zeroes_like_tensor))


tf.Tensor(12, shape=(), dtype=int32)


In [ ]:
random_tensor = tf.random.normal(
  [3,2],
  mean = 0.0,
  stddev=1.0
)
print(random_tensor)

tf.Tensor(
[[ 0.72422004  0.43045303]
 [-0.23500958 -0.10795611]
 [ 2.1620815  -0.86860967]], shape=(3, 2), dtype=float32)


In [ ]:
uniform_random_tensor = tf.random.uniform(
    [2,2],
    minval=10,
    maxval=20
)
print(uniform_random_tensor)

tf.Tensor(
[[13.574423 18.172806]
 [11.166715 19.416168]], shape=(2, 2), dtype=float32)


In [ ]:
tf.random.set_seed(42)
matrix = tf.random.uniform(shape=[2,2],minval=10,maxval=100,seed=42)
print(matrix)

tf.Tensor(
[[47.46725  34.172348]
 [53.171486 42.81142 ]], shape=(2, 2), dtype=float32)


# Indexing in Tenserflow

In [ ]:
tensor_indexed = tf.constant([2,3,4,5,6,7,8,1,0])
print(tensor_indexed[3])

tf.Tensor(5, shape=(), dtype=int32)


In [ ]:
print(tensor_indexed[-1])

tf.Tensor(0, shape=(), dtype=int32)


In [ ]:
print(tensor_indexed[1:5])

tf.Tensor([3 4 5 6], shape=(4,), dtype=int32)


In [ ]:
print(tensor_indexed[::2])

tf.Tensor([2 4 6 8 0], shape=(5,), dtype=int32)


In [ ]:
tensor_indexes = tf.constant([
    [2,3,4,5,6],
    [9,0,4,2,1],
    [0,0,1,7,0]
])
print(tensor_indexes)

tf.Tensor(
[[2 3 4 5 6]
 [9 0 4 2 1]
 [0 0 1 7 0]], shape=(3, 5), dtype=int32)


In [ ]:
print(tensor_indexes[1,0])

tf.Tensor(9, shape=(), dtype=int32)


In [ ]:
print(tensor_indexes[1,1:4])

tf.Tensor([0 4 2], shape=(3,), dtype=int32)


In [ ]:
print(tensor_indexes[:2,-1])

tf.Tensor([6 1], shape=(2,), dtype=int32)


In [ ]:
print(tensor_indexes[:,-1])

tf.Tensor([6 1 0], shape=(3,), dtype=int32)


In [ ]:
print(tensor_indexes[:2,2:4])

tf.Tensor(
[[4 5]
 [4 2]], shape=(2, 2), dtype=int32)


In [ ]:
tensor_three_d = tf.constant(
[
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]]
])

In [ ]:
print(tensor_three_d[:2,:,:2])

tf.Tensor(
[[[1 2]
  [4 5]]

 [[1 2]
  [4 5]]], shape=(2, 2, 2), dtype=int32)


# Mathematics Operations

In [ ]:
x = tf.constant(-4)
print(tf.abs(x))

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
x = tf.constant([2,3,4,5])
y = tf.constant([1,1,1,1])

print(tf.add(x,y))

tf.Tensor([3 4 5 6], shape=(4,), dtype=int32)


In [ ]:
x = tf.constant([2,3,4,5])
y = tf.constant(3)

print(tf.add(x,y))

tf.Tensor([5 6 7 8], shape=(4,), dtype=int32)


In [ ]:
x = tf.constant([2,3,4,5])
y = tf.constant(0)

print(tf.divide(x,y))
print(tf.math.divide_no_nan(x,y))


tf.Tensor([inf inf inf inf], shape=(4,), dtype=float64)
tf.Tensor([0. 0. 0. 0.], shape=(4,), dtype=float64)


In [ ]:
x = tf.constant([2,3,4,5])
y = tf.constant([2,-3,4,5])
print(tf.math.maximum(x,y))

tf.Tensor([2 3 4 5], shape=(4,), dtype=int32)


In [ ]:
print(tf.math.minimum(x,y))

tf.Tensor([ 2 -3  4  5], shape=(4,), dtype=int32)


In [ ]:
x = tf.constant([2,3,4,5])
print(tf.math.argmax(x))

tf.Tensor(3, shape=(), dtype=int64)


In [ ]:
print(tf.math.argmin(x))


tf.Tensor(0, shape=(), dtype=int64)


In [ ]:
x = tf.constant([2,3,4,5])
y = tf.constant([2,-3,4,5])

print(tf.math.equal(x,y))

tf.Tensor([ True False  True  True], shape=(4,), dtype=bool)


In [ ]:
print(tf.math.pow(y,x))

tf.Tensor([   4  -27  256 3125], shape=(4,), dtype=int32)


In [ ]:
input_tensor = tf.constant([5,4,3,1])
print(tf.math.reduce_max(input_tensor))

tf.Tensor(5, shape=(), dtype=int32)


In [ ]:
print(tf.math.reduce_sum(input_tensor))
print(tf.math.reduce_sum(input_tensor,keepdims=True))

tf.Tensor(13, shape=(), dtype=int32)
tf.Tensor([13], shape=(1,), dtype=int32)


In [ ]:
result = tf.math.top_k([1, 2, 98, 1, 1, 99, 3, 1, 3, 96, 4, 1],
                        k=3)
print(result)


TopKV2(values=<tf.Tensor: shape=(3,), dtype=int32, numpy=array([99, 98, 96], dtype=int32)>, indices=<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 2, 9], dtype=int32)>)


# Variable in Tensorflow

In [ ]:
x = tf.constant([1,2,3,4,5])
x_var = tf.Variable(x)
print(x_var)

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>


In [ ]:
x_var.assign([5,4,3,2,1])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([5, 4, 3, 2, 1], dtype=int32)>

# String Tensors

In [ ]:
tensor_string = tf.constant(["i am","a","string"])
print(tensor_string)

tf.Tensor([b'i am' b'a' b'string'], shape=(3,), dtype=string)


In [ ]:
tf.strings.join(tensor_string,separator="+")

<tf.Tensor: shape=(), dtype=string, numpy=b'i am+a+string'>

In [ ]:
tensor_string_one = tf.constant(["i am","a","string"])
tensor_string_two = tf.constant(["i am","not a","string"])
tf.strings.join([tensor_string_one, tensor_string_two],separator="+")

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'i am+i am', b'a+not a', b'string+string'], dtype=object)>

# Sparse Tensors

In [ ]:
sparse_tensor = tf.sparse.SparseTensor(
    indices=[[0,0],
             [1,2]], values=[1,5], dense_shape=[5,6]
)

print(sparse_tensor)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 5], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))


In [ ]:
tf.sparse.to_dense(sparse_tensor)

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[1, 0, 0, 0, 0, 0],
       [0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int32)>

# Ragged Tensors

In [ ]:
a = tf.ragged.constant([
    [1,3],
    [4,5,6],
    [7]
])
print(a)

<tf.RaggedTensor [[1, 3], [4, 5, 6], [7]]>


In [ ]:
tf.ragged.boolean_mask(  # Mask a 2D Tensor.
    data=[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    mask=[[True, False, True], [False, False, False], [True, False, False]]).to_list()


[[1, 3], [], [7]]

# Common Methods

In [80]:
a  = tf.constant([1,2,3,4,5,6,7])
a.shape

TensorShape([7])

In [81]:
tf.expand_dims(a,axis=0)

<tf.Tensor: shape=(1, 7), dtype=int32, numpy=array([[1, 2, 3, 4, 5, 6, 7]], dtype=int32)>

In [82]:
tf.expand_dims(a,axis=1)

<tf.Tensor: shape=(7, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]], dtype=int32)>

In [83]:
b = tf.constant(
[
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]]
])

print(b.shape)

(4, 2, 3)


In [85]:
c =tf.expand_dims(b,axis=0)
print(c.shape)

(1, 4, 2, 3)


In [86]:
print(tf.squeeze(c,axis=0))

tf.Tensor(
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]], shape=(4, 2, 3), dtype=int32)


In [89]:
d = tf.constant([1,2,3,4,5,6,7,8,9])
print(tf.reshape(d,[3,3]))

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [92]:
t1 = [[1, 2, 3], [4, 5, 6]]
t2 = [[7, 8, 9], [10, 11, 12]]
tf.concat([t1, t2], 0)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [93]:
t = tf.constant([
    [1,2,3],
    [2,3,4]
])

paddings = tf.constant([[2,2],
                         [1,1]])
print(tf.pad(t,paddings,"CONSTANT"))

tf.Tensor(
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 2 3 0]
 [0 2 3 4 0]
 [0 0 0 0 0]
 [0 0 0 0 0]], shape=(6, 5), dtype=int32)


In [94]:
a = tf.constant([2,3,4,5,6])
print(a[1:3])

tf.Tensor([3 4], shape=(2,), dtype=int32)


In [95]:
tf.gather(a,[0,3,1],axis=0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 5, 3], dtype=int32)>

## Linear Algebra

In [ ]:
x1 = tf.constant([[1,2],[3,4]])
x2 = tf.constant([[1,2],[2,1]])

print(tf.linalg.matmul(x1,x2))

tf.Tensor(
[[ 5  4]
 [11 10]], shape=(2, 2), dtype=int32)


In [ ]:
x1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
tf.transpose(x1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4]], dtype=int32)>

In [ ]:
input_mat = [[2,3],[-1,-2]]
tf.linalg.band_part(
    input_mat,
    0,
    1,
)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2,  3],
       [ 0, -2]], dtype=int32)>

In [ ]:
input_mat = tf.constant([[2,3],[-1,-2]], dtype=tf.float32)
tf.linalg.inv(input_mat)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 2.,  3.],
       [-1., -2.]], dtype=float32)>

In [ ]:
A =   np.array([[1,2,3,4],
                [5,6,7,8]])

np.einsum("ij -> ji",A)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
tensor_three_d = tf.constant([
    [[1,2,3],
     [4,5,6]],
    [[5,6,7],
     [8,9,0]]
])
print(tensor_three_d.shape)
print(tf.expand_dims(tensor_three_d,axis=0).shape)

(2, 2, 3)
(1, 2, 2, 3)


In [ ]:
x= tf.constant([1,2,3,4,5,6])
print(x.shape)
x_expanded = tf.expand_dims(x,axis=0)

(6,)


In [ ]:
print(x_expanded)

tf.Tensor([[1 2 3 4 5 6]], shape=(1, 6), dtype=int32)


In [ ]:
x_sequeeze = tf.squeeze(x_expanded,axis=0)
print(x_sequeeze)

tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


In [ ]:
print(tf.reshape(x_sequeeze,[2,3]))

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [ ]:
print(tf.reshape(x_sequeeze,[-1]))


tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


In [ ]:
t1 =[[1,2,3],[4,5,6]]
t2 =[[1,2,3],[4,5,6]]

print(t1)
print(t2)
print(tf.concat([t1,t2],0))
print(tf.concat([t1,t2],1))


[[1, 2, 3], [4, 5, 6]]
[[1, 2, 3], [4, 5, 6]]
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]], shape=(2, 6), dtype=int32)


In [ ]:
t1 =[[[1,2,3],[4,5,6]]]
t2 =[[[1,2,3],[4,5,6]]]

print(t1)
print(t2)
print(tf.concat([t1,t2],0))
print(tf.concat([t1,t2],1))

[[[1, 2, 3], [4, 5, 6]]]
[[[1, 2, 3], [4, 5, 6]]]
tf.Tensor(
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]], shape=(2, 2, 3), dtype=int32)
tf.Tensor(
[[[1 2 3]
  [4 5 6]
  [1 2 3]
  [4 5 6]]], shape=(1, 4, 3), dtype=int32)


In [ ]:
print(tf.stack([t1,t2],1))

tf.Tensor(
[[[[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]]], shape=(1, 2, 2, 3), dtype=int32)


In [ ]:
print(tf.stack([t1,t2],0))


tf.Tensor(
[[[[1 2 3]
   [4 5 6]]]


 [[[1 2 3]
   [4 5 6]]]], shape=(2, 1, 2, 3), dtype=int32)
