In [1]:
import tensorflow as tf

# Vecotors and Metrice

In [2]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
tensor_one_d = tf.constant([2,0,-3.])
print(tensor_one_d)

tf.Tensor([ 2.  0. -3.], shape=(3,), dtype=float32)


In [4]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,9]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  9]], shape=(4, 3), dtype=int32)


In [5]:
tensor_three_d = tf.constant(
[
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]]
])
print(tensor_three_d)

tf.Tensor(
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]], shape=(4, 2, 3), dtype=int32)


## Shape of tensor

In [6]:
print(tensor_three_d.shape)

(4, 2, 3)


## Dimensions of Matrix

In [7]:
print(tensor_three_d.ndim)

3


In [8]:
tensor_four_d = tf.constant(
[
  [
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]]
  ],
  [
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]]
  ]
]
)
print(tensor_four_d)

tf.Tensor(
[[[[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]]


 [[[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]]], shape=(2, 4, 2, 3), dtype=int32)


## Tensor Casting

In [9]:
tensor_one_d = tf.constant([1,2,3,4,5], dtype=tf.float32)
print(tensor_one_d)
casted_tensor = tf.cast(tensor_one_d,dtype=tf.int16)
print(casted_tensor)

tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int16)


In [10]:
casted_tensor_bool = tf.cast(tensor_one_d,dtype=tf.bool)
print(casted_tensor_bool)

tf.Tensor([ True  True  True  True  True], shape=(5,), dtype=bool)


In [11]:
tensor_string = tf.constant("Hello World")
print(tensor_string)

tf.Tensor(b'Hello World', shape=(), dtype=string)


## Convert Numpy Array to Tensor

In [12]:
import numpy as np

In [13]:
np_array = np.array([1,2,4,5])
print(np_array)

[1 2 4 5]


In [14]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4 5], shape=(4,), dtype=int64)


## Identity Matrix

In [16]:
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=[2],
    dtype=tf.dtypes.float32,
    name=None
)

print(eye_tensor)

tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]], shape=(2, 3, 3), dtype=float32)


## Tenserflow Method

In [17]:
fill_tensor = tf.fill(
    [3,4], value=5, name=None, layout=None
)
print(fill_tensor)

tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)


In [18]:
ones_tensor = tf.ones([2,3])
print(ones_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [20]:
ones_like_tensor = tf.ones_like(fill_tensor)
print(ones_like_tensor)

tf.Tensor(
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]], shape=(3, 4), dtype=int32)


In [21]:
zeroes_tensor = tf.zeros([2,4])
print(zeroes_tensor)

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(2, 4), dtype=float32)


In [22]:
zeroes_like_tensor = tf.zeros_like(fill_tensor)
print(zeroes_like_tensor)

tf.Tensor(
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)


In [23]:
print(tf.shape(zeroes_like_tensor))

tf.Tensor([3 4], shape=(2,), dtype=int32)


In [24]:
print(tf.rank(zeroes_like_tensor))

tf.Tensor(2, shape=(), dtype=int32)


In [25]:
print(tf.size(zeroes_like_tensor))


tf.Tensor(12, shape=(), dtype=int32)


In [26]:
random_tensor = tf.random.normal(
  [3,2],
  mean = 0.0,
  stddev=1.0
)
print(random_tensor)

tf.Tensor(
[[ 0.72422004  0.43045303]
 [-0.23500958 -0.10795611]
 [ 2.1620815  -0.86860967]], shape=(3, 2), dtype=float32)


In [28]:
uniform_random_tensor = tf.random.uniform(
    [2,2],
    minval=10,
    maxval=20
)
print(uniform_random_tensor)

tf.Tensor(
[[13.574423 18.172806]
 [11.166715 19.416168]], shape=(2, 2), dtype=float32)


In [32]:
tf.random.set_seed(42)
matrix = tf.random.uniform(shape=[2,2],minval=10,maxval=100,seed=42)
print(matrix)

tf.Tensor(
[[47.46725  34.172348]
 [53.171486 42.81142 ]], shape=(2, 2), dtype=float32)
